server:
  port: 8080
spring:
  application.name: MyECommerce
  liquibase:
    enabled: true
  # Configuration for MySQL Database
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: E_Commerce
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
